ServerName localhost
ServerTokens Prod
ServerSignature Off
<Directory /var/www/html>
    Options -Indexes
    AllowOverride All
    Require all granted
</Directory>
<Directory /var/www/html/arquivos>
    Options -Indexes -ExecCGI
    AllowOverride None
    <FilesMatch "(?i)\.(php[0-9]?|phtml|phar|cgi|pl|py|sh|shtml|html?|svg|js|htaccess)(\.|$)">
        Require all denied
    </FilesMatch>
    Header always set X-Content-Type-Options "nosniff"
</Directory>
