upload_max_filesize=10M
post_max_size=64M
max_file_uploads=40
memory_limit=256M
date.timezone=America/Sao_Paulo
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
expose_php=Off
opcache.enable=1
