<?php
require __DIR__ . '/about.php';
$before = $count;
$fixture = require __DIR__ . '/fixtures/humanization.php';
Read::$fixtures = $fixture;
$getPagina = new Read();
$r_DIR = array('page'=>'humanizacao', 'info'=>array('titulo'=>'Humanização'));
ob_start(); require DIR.'includes/header.php'; require DIR.'includes/paginas/humanizacao.php'; require DIR.'includes/footer.php'; $html=ob_get_clean();
verify(!str_contains($html,'jQuery') && !str_contains($html,'bootstrap.min') && !str_contains($html,'owlCarousel') && !str_contains($html,'resources/css/style.css'), 'Humanization without legacy dependencies');
verify(str_contains($html,'humanization.css') && str_contains($html,'about.js'), 'Load page styles and shared gallery');
verify(str_contains($html,'Acolher faz parte') && str_contains($html,'conteúdo institucional') && str_contains($html,'segundo bloco') && str_contains($html,'Primeira melhoria'), 'Preserve all four CMS blocks');
verify(str_contains($html,'2010') && str_contains($html,'Sempre evoluindo'), 'Preserve original evolution context');
verify(substr_count($html,'class="about-slide"') === count($fixture['galeria_humanizacao']), 'Render each image once, not duplicated for mobile');
verify(str_contains($html,'/hospital/arquivos/galeria_humanizacao/'), 'Subdirectory image URLs');
verify(str_contains($html,'aria-controls="humanization-gallery-track"'), 'Gallery controls target correct region');
verify(str_contains($html,'Galeria de humanização: imagem ampliada'), 'Dialog has page-specific accessible name');
Read::$fixtures = array_fill_keys(array_keys($fixture), array());
ob_start(); require DIR.'includes/paginas/humanizacao.php'; $html=ob_get_clean();
verify(str_contains($html,'As informações sobre humanização serão disponibilizadas'), 'Empty content message');
verify(!str_contains($html,'href="#humanizacao-') && !str_contains($html,'<dialog'), 'No empty navigation or gallery');
Read::$fixtures = $fixture;
Read::$fixtures['galeria_humanizacao'] = array_slice($fixture['galeria_humanizacao'],0,1);
ob_start(); require DIR.'includes/paginas/humanizacao.php'; $html=ob_get_clean();
verify(substr_count($html,'class="about-slide"') === 1, 'One image');
Read::$fixtures = array('pagina_humanizacao'=>array(), 'galeria_humanizacao'=>$fixture['galeria_humanizacao']);
ob_start(); require DIR.'includes/paginas/humanizacao.php'; $html=ob_get_clean();
verify(str_contains($html,'href="#humanizacao-galeria"') && !str_contains($html,'href="#humanizacao-cuidado"'), 'Gallery-only content');
Read::$fixtures = array('pagina_humanizacao'=>array(array('bloco4'=>'<p>Melhorias isoladas</p>')), 'galeria_humanizacao'=>array());
ob_start(); require DIR.'includes/paginas/humanizacao.php'; $html=ob_get_clean();
verify(str_contains($html,'Melhorias isoladas') && !str_contains($html,'<dialog'), 'Evolution-only content');
Read::$fixtures = $fixture;
Read::$fixtures['pagina_humanizacao'][0]['bloco2'] = '<script>alert(1)</script><p onclick="evil()">Texto seguro</p>';
Read::$fixtures['galeria_humanizacao'] = array(array('img'=>'javascript:alert(1)','descricao'=>'Bad'),array('img'=>'resources/img/no-image.png','descricao'=>'<b>Legenda</b> " segura'));
ob_start(); require DIR.'includes/paginas/humanizacao.php'; $html=ob_get_clean();
verify(!str_contains($html,'<script>') && !str_contains($html,'onclick=') && str_contains($html,'Texto seguro'), 'Sanitize CMS content');
verify(!str_contains($html,'javascript:') && substr_count($html,'class="about-slide"') === 1, 'Reject executable image links');
verify(str_contains($html,'Legenda &quot; segura'), 'Escape gallery metadata');
echo 'OK: ' . ($count-$before) . " humanization checks.\n";
