const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict'),{spawn,spawnSync}=require('child_process');
const php=process.argv[2]||'php',root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'scl-mysql-')),stateFile=path.join(temp,'state.json'),base='http://127.0.0.1:18105';
let server,cookie='',csrf='',checks=0,logs='',uploadPaths=new Set();
function setup(mode){const r=spawnSync(php,[path.join(__dirname,'mysql-setup.php'),mode,stateFile],{cwd:root,encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error(r.stderr||r.stdout);return r.stdout;}
async function req(url,options={}){const r=await fetch(base+url,{...options,redirect:'manual',headers:{...options.headers,...(cookie?{Cookie:cookie}:{})}});const set=r.headers.getSetCookie();if(set.length)cookie=set.at(-1).split(';')[0];return r;}
async function post(url,data){const body=data instanceof FormData?data:new URLSearchParams(data);const r=await req(url,{method:'POST',headers:{'X-CSRF-Token':csrf},body});const text=await r.text();assert.equal(r.status,200,url+' '+(data instanceof FormData?data.get('acao'):data.acao)+': '+text.slice(0,200)+' '+logs.split('\n').filter(l=>/SCL/.test(l)).slice(-4).join('\n'));checks++;return text;}
function track(url){if(typeof url==='string'&&/^arquivos\/[a-z_]+\/\d{4}\/\d{2}\/[a-f0-9]{48}\.(png|jpg|pdf)$/.test(url))uploadPaths.add(url);}
function dataFields(form){const data={};for(const m of form.matchAll(/<(input|textarea|select)\b([^>]*)>/g)){const name=m[2].match(/name=["']([^"']+)["']/)?.[1];if(!name||m[2].includes('type="file"')||m[2].includes("type='file'"))continue;if(name==='id')continue;data[name]=name==='ano'?'2026':/^data[12]$/.test(name)?'2026':'Validação MySQL';}return data;}
(async()=>{try{
 console.log(setup('create').trim());const state=JSON.parse(fs.readFileSync(stateFile));
 server=spawn(php,['-d','upload_max_filesize=10M','-d','post_max_size=64M','-d','memory_limit=256M','-S','127.0.0.1:18105','-t',root,path.join(root,'router.php')],{cwd:root,env:{...process.env,SCL_DB_NAME:state.database,SCL_DB_PREFIX:state.prefix,SCL_HOME:base+'/',SCL_SMTP_HOST:'127.0.0.1',SCL_SMTP_PORT:'9'},windowsHide:true,stdio:['ignore','ignore','pipe']});server.stderr.on('data',d=>logs+=d);
 for(let i=0;i<60;i++){try{await fetch(base+'/admin/index.php');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 let r=await req('/admin/index.php'),html=await r.text();csrf=html.match(/name="_csrf" value="([^"]+)"/)[1];r=await req('/admin/index.php',{method:'POST',body:new URLSearchParams({action:'login',usuario:state.username,senha:state.password,_csrf:csrf})});assert.equal(r.status,303,'real login');checks++;
 r=await req('/admin/painel.php');html=await r.text();csrf=html.match(/name="csrf-token" content="([^"]+)"/)[1];
 const pageForms={};
 for(const route of ['home','usuario/index','usuario/create','usuario/update','noticias/index','noticias/create','noticias/update','banner/index','banner/create','banner/update','galeria/index','galeria/create','galeria/update','paginas/institucional','paginas/instalacoes','paginas/servicos','paginas/fale-conosco','atendimento','relatorios']){r=await req('/admin/painel.php?exe='+route+'&id_usuario='+state.userId+'&id_noticia=1&id_banner=1&id_galeria=1');html=await r.text();assert.equal(r.status,200,route);assert(html.includes('<h1'),route);if(route!=='home')assert(!html.includes('O que vamos atualizar hoje?'),route+' returned home');checks++;
 if(route.startsWith('paginas/'))pageForms[route]=html;
 }
 for(const group of ['institucional','instalacoes','servicos','fale-conosco']){const source=fs.readFileSync(path.join(root,'admin/webservices/paginas',group,'servico.php'),'utf8');for(const match of source.matchAll(/case '(get[^']+|list[^']+)':/g)){const text=await post('/admin/webservices/paginas/'+group+'/servico.php',{acao:match[1],id:1,id_unidade_internacao:1,id_capacidade:1});assert.doesNotThrow(()=>JSON.parse(text),group+' '+match[1]+' not JSON');}}
 for(const channel of ['contatos','ouvidoria','curriculos','doacoes','pesquisa']){r=await req('/admin/atendimento-api.php?canal='+channel);assert.equal(r.status,200);assert(Array.isArray((await r.json()).rows));checks++;r=await req('/admin/atendimento-api.php?canal='+channel+'&exportar=csv');assert.equal(r.status,200);assert(r.headers.get('content-type').includes('text/csv'));await r.arrayBuffer();checks++;}
 for(const [route,source] of Object.entries(pageForms)){const form=source.match(/<form\b[^>]*id=["']paginasForm["'][^>]*>([\s\S]*?)<\/form>/);assert(form,route+' page form');const data=dataFields(form[1]);assert.equal((await post('/admin/webservices/paginas/servico.php',{...data,acao:'updatePaginas'})).trim(),'1',route+' save');}
 const png=fs.readFileSync(path.join(root,'resources/img/icon-logo.png'));
 for(const [route,source] of Object.entries(pageForms)){for(const match of source.matchAll(/<form\b[^>]*id=["']form-create-([^"']+)["'][^>]*>([\s\S]*?)<\/form>/g)){const domain=match[1],data=dataFields(match[2]),body=new FormData();for(const[k,v]of Object.entries(data))body.set(k,v);body.set('acao','createConteudo');body.set('dominio',domain);const fileName=match[2].match(/<input[^>]*type=["']file["'][^>]*name=["']([^"']+)/)?.[1];if(fileName){const pdf=/balanco|download_manual/.test(domain);body.set(fileName,new Blob([pdf?Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF'):png],{type:pdf?'application/pdf':'image/png'}),pdf?'teste.pdf':'teste.png');}
 const id=Number(await post('/admin/webservices/paginas/servico.php',body));assert(id>0,domain+' create');const item=JSON.parse(await post('/admin/webservices/paginas/servico.php',{acao:'getConteudo',dominio:domain,id}));track(item.img);track(item.pdf);
 assert.equal((await post('/admin/webservices/paginas/servico.php',{...data,acao:'updateConteudo',dominio:domain,id})).trim(),'1',domain+' update');assert.equal((await post('/admin/webservices/paginas/servico.php',{acao:'excluiConteudo',dominio:domain,id})).trim(),'1',domain+' delete');
 }}
 const gallery=JSON.parse(await post('/admin/galeria-api.php',{acao:'create',nome:'Validação MySQL'}));const image=new FormData();image.set('acao','upload');image.set('id_galeria',gallery.id);image.set('image',new Blob([png,Buffer.alloc(3*1024*1024)],{type:'image/png'}),'teste.png');const photo=JSON.parse(await post('/admin/galeria-api.php',image));track(photo.url);assert(photo.id_anexo>0);assert(JSON.parse(await post('/admin/galeria-api.php',{acao:'save',id_galeria:gallery.id,nome:'Galeria validada',photos:JSON.stringify([{id_anexo:photo.id_anexo,legenda:'Legenda MySQL'}])})).success);
 for(const kind of ['banner','noticias']){const entity=kind==='noticias'?'Noticia':'Banner',endpoint='/admin/webservices/'+kind+'/servico.php';const fields={titulo:'Validação '+Date.now(),link:'teste-mysql-'+Date.now(),status:'1',...(kind==='noticias'?{subtitulo:'Resumo',descricao:'<p>Conteúdo</p>','id_tag[]':'Categoria '+Date.now()}:{})};const body=new FormData();for(const[k,v]of Object.entries(fields))body.set(k,v);body.set('acao','New'+entity);body.set('img',new Blob([png],{type:'image/png'}),'teste.png');const id=Number(await post(endpoint,body));assert(id>0,kind+' create');const rows=JSON.parse(await post(endpoint,{acao:'Get'+entity,['Id'+entity]:id}));track(rows[0].img);assert.equal((await post(endpoint,{...fields,acao:'Update'+entity,[kind==='noticias'?'id_noticia':'id_banner']:id,img:rows[0].img})).trim(),'1');assert.equal((await post(endpoint,{acao:'Delete'+entity,['Id'+entity]:id})).trim(),'ok');}
 const users='/admin/webservices/usuario/servico.php',newUser={nome:'Nome '.repeat(20),email:'test-'+Date.now()+'@example.invalid',usuario:'test_'+Date.now(),senha:'Testing secure account password',status:'1'};
 const userId=Number(await post(users,{...newUser,acao:'createUser'}));assert(userId>0);let account=JSON.parse(await post(users,{acao:'getUser',id_usuario:userId}));assert.equal(account.nome,newUser.nome.trim());assert.equal((await post(users,{...newUser,senha:'',status:'0',acao:'updateUser',id_usuario:userId})).trim(),'1');account=JSON.parse(await post(users,{acao:'getUser',id_usuario:userId}));assert.equal(account.status,0);assert.equal((await post(users,{acao:'excluiUser',id_usuario:userId})).trim(),'1');
 for(const [group,suffix,statusAction] of [['instalacoes','UnidadeInternacao','alteraStatusUnidadeInternacao'],['servicos','Capacidade','alteraStatusImagemCapacidade']]){const endpoint='/admin/webservices/paginas/'+group+'/servico.php',body=new FormData();body.set('acao','insereImagem'+suffix);body.set('id','1');body.set('img',new Blob([png],{type:'image/png'}),'teste.png');const item=JSON.parse(await post(endpoint,body));track(item.img);assert(item.id>0);assert.equal((await post(endpoint,{acao:statusAction,id_imagem:item.id,status:'1'})).trim(),'1');assert.equal((await post(endpoint,{acao:'excluiImagem'+suffix,id_imagem:item.id})).trim(),'1');}
 const jpegFile=fs.readdirSync(path.join(root,'resources/img'),{recursive:true}).find(name=>/\.jpe?g$/i.test(name));assert(jpegFile,'JPEG fixture available');const jpegUpload=new FormData();jpegUpload.set('acao','upload');jpegUpload.set('id_galeria',gallery.id);jpegUpload.set('image',new Blob([fs.readFileSync(path.join(root,'resources/img',jpegFile))],{type:'image/jpeg'}),'teste.jpg');const jpegPhoto=JSON.parse(await post('/admin/galeria-api.php',jpegUpload));track(jpegPhoto.url);assert(jpegPhoto.id_anexo>0);
 const publicGallery=JSON.parse(await post('/includes/servicos/galeria.php',{acao:'getGalleria',galleria:gallery.id}));assert.equal(publicGallery[0].descricao,'Legenda MySQL');
 const publicRun=spawnSync(php,[path.join(__dirname,'mysql-public.php')],{cwd:root,env:{...process.env,SCL_DB_PREFIX:state.prefix},encoding:'utf8',windowsHide:true});assert.equal(publicRun.status,0,publicRun.stderr);assert(publicRun.stdout.includes('OK:'),publicRun.stdout);console.log(publicRun.stdout.trim());
 console.log('OK: '+checks+' MySQL HTTP checks; real schema and cloned data, no production content changes.');
 const errors=logs.split('\n').filter(l=>/SCL exception|SCL PHP error|database operation failed/.test(l));assert.equal(errors.length,0,errors.join('\n'));
 }finally{if(server){server.kill();await new Promise(resolve=>{if(server.exitCode!==null)return resolve();server.once('exit',resolve);});}if(fs.existsSync(stateFile))console.log(setup('drop').trim());for(const relative of uploadPaths){const file=path.resolve(root,relative);if(!file.startsWith(path.join(root,'arquivos')+path.sep))throw Error('Unsafe upload cleanup');if(fs.existsSync(file))fs.unlinkSync(file);}if(!temp.startsWith(path.join(os.tmpdir(),'scl-mysql-')))throw Error('Unsafe cleanup');fs.rmSync(temp,{recursive:true});}
})().catch(e=>{console.error(e.stack);console.error(logs.split("\n").filter(l=>/SCL/.test(l)).slice(-6).join("\n"));process.exitCode=1;});
