<?php
require __DIR__ . '/social-actions.php';
$before = $count;
$fixture = require __DIR__ . '/fixtures/patient-safety.php';
Read::$fixtures = $fixture;
Read::$queries = array();
$getPagina = new Read();
$r_DIR = array('page'=>'programa-nacional-seguranca','info'=>array('titulo'=>'Programa de segurança do paciente'));
ob_start(); require DIR.'includes/header.php'; require DIR.'includes/topo_paginas.php'; require DIR.'includes/paginas/programa_nacional_seguranca.php'; require DIR.'includes/footer.php'; $html=ob_get_clean();
verify(!str_contains($html,'jQuery') && !str_contains($html,'bootstrap.min') && !str_contains($html,'owlCarousel') && !str_contains($html,'resources/css/style.css'), 'No legacy dependencies');
verify(str_contains($html,'patient-safety.css') && !str_contains($html,'about.js'), 'No gallery script for static content');
verify(substr_count($html,'<h1>') === 1, 'One page heading');
verify(str_contains($html,'exibe integralmente') && str_contains($html,'informações sobre o Núcleo'), 'Preserve both CMS blocks');
verify(str_contains($html,'Programa nacional de segurança do paciente') && str_contains($html,'Núcleo de segurança do paciente'), 'Preserve section titles');
verify(str_contains($html,'/hospital/arquivos/programa_nacional_seguranca/'), 'Image URL supports subdirectories');
verify(str_contains($html,'Abrir imagem do núcleo de segurança do paciente em tamanho original'), 'Accessible original image link');
verify(str_contains($html,'/hospital/servicos/manual-do-paciente-e-visitantes') && str_contains($html,'/hospital/fale-conosco'), 'Existing information and contact links');
verify(count(Read::$queries) >= 1 && str_contains(Read::$queries[0]['sql'],'pagina_programa_nacional_seguranca ORDER BY data DESC LIMIT 1'), 'Retain latest CMS record query');
Read::$fixtures = array('pagina_programa_nacional_seguranca'=>array());
ob_start(); require DIR.'includes/paginas/programa_nacional_seguranca.php'; $html=ob_get_clean();
verify(str_contains($html,'As informações sobre o programa serão disponibilizadas'), 'Empty state');
verify(!str_contains($html,'href="#seguranca-programa"') && !str_contains($html,'class="safety-image"'), 'No broken navigation or image when empty');
Read::$fixtures = array('pagina_programa_nacional_seguranca'=>array(array('bloco1'=>'Programa isolado')));
ob_start(); require DIR.'includes/paginas/programa_nacional_seguranca.php'; $html=ob_get_clean();
verify(str_contains($html,'Programa isolado') && !str_contains($html,'id="seguranca-nucleo"'), 'Program-only record');
Read::$fixtures = array('pagina_programa_nacional_seguranca'=>array(array('bloco2'=>'Núcleo isolado')));
ob_start(); require DIR.'includes/paginas/programa_nacional_seguranca.php'; $html=ob_get_clean();
verify(str_contains($html,'Núcleo isolado') && str_contains($html,'safety-single-column') && !str_contains($html,'id="seguranca-programa"'), 'Core-only record without image');
Read::$fixtures = array('pagina_programa_nacional_seguranca'=>array(array('img1'=>$fixture['pagina_programa_nacional_seguranca'][0]['img1'])));
ob_start(); require DIR.'includes/paginas/programa_nacional_seguranca.php'; $html=ob_get_clean();
verify(str_contains($html,'class="safety-image"') && !str_contains($html,'class="about-prose safety-core-copy"'), 'Image-only record');
Read::$fixtures = array('pagina_programa_nacional_seguranca'=>array(array('bloco1'=>'<script>evil()</script><p onclick="evil()">Conteúdo seguro</p>', 'bloco2'=>"<ul><li>Item cadastrado</li></ul>", 'img1'=>'javascript:evil()')));
ob_start(); require DIR.'includes/paginas/programa_nacional_seguranca.php'; $html=ob_get_clean();
verify(!str_contains($html,'<script>') && !str_contains($html,'onclick=') && str_contains($html,'Conteúdo seguro'), 'Safe content rendering');
verify(str_contains($html,'<ul><li>Item cadastrado</li></ul>'), 'Keep CMS lists');
verify(!str_contains($html,'javascript:') && !str_contains($html,'class="safety-image"'), 'Reject unsafe image URLs');
$r_DIR['page'] = 'programa_nacional_seguranca';
ob_start(); require DIR.'includes/header.php'; $html=ob_get_clean();
verify(str_contains($html,'patient-safety.css') && !str_contains($html,'jQuery'), 'Underscore alias has modern assets');
echo 'OK: ' . ($count-$before) . " patient-safety checks.\n";
