<?php
require __DIR__ . '/humanization.php';
$before = $count;
$fixture = require __DIR__ . '/fixtures/social-actions.php';
Read::$fixtures = $fixture;
Read::$queries = array();
$getPagina = new Read();
$r_DIR = array('page'=>'acoes-sociais-ambientais', 'info'=>array('titulo'=>'Ações sociais e ambientais'));
ob_start(); require DIR.'includes/header.php'; require DIR.'includes/topo_paginas.php'; require DIR.'includes/paginas/acoes_sociais_ambientais.php'; require DIR.'includes/footer.php'; $html=ob_get_clean();
verify(!str_contains($html,'jQuery') && !str_contains($html,'bootstrap.min') && !str_contains($html,'owlCarousel') && !str_contains($html,'resources/css/style.css'), 'No legacy dependencies');
verify(str_contains($html,'social-actions.css') && str_contains($html,'about.js'), 'Dedicated style and shared gallery');
verify(str_contains($html,'apoio religioso') && str_contains($html,'texto introdutório') && str_contains($html,'acompanha a galeria') && str_contains($html,'Primeira orientação'), 'Preserve four content blocks');
verify(substr_count($html,'<h1>') === 1, 'Single primary heading');
verify(str_contains($html,'/hospital/arquivos/acoes_sociais_ambientais/'), 'Preserve featured image with subdirectory');
verify(substr_count($html,'class="about-slide"') === count($fixture['galeria_acao']), 'No duplicate gallery images');
verify(str_contains($html,'aria-controls="social-gallery-track"'), 'Correct gallery region');
verify(substr_count($html,'class="news-card"') === 3, 'Related news cards');
verify(str_contains($html,'/hospital/noticias/acoes-sociais'), 'Link to category');
verify(str_contains($html,'/hospital/noticias/acao-demonstrativa-1'), 'Article URLs');
verify(str_contains($html,'/hospital/resources/img/no-image.png'), 'Missing news image fallback');
$newsCalls = array_values(array_filter(Read::$queries, function ($call) { return str_contains($call['sql'], 'SELECT N.*'); }));
verify(count($newsCalls) === 1 && $newsCalls[0]['params'] === 'tag=acoes-sociais', 'Bind social category in news query');
verify(str_contains($newsCalls[0]['sql'],'N.status = 1') && str_contains($newsCalls[0]['sql'],'EXISTS') && str_contains($newsCalls[0]['sql'],'ORDER BY N.data_criacao DESC LIMIT 3'), 'Query published latest news without tag duplication');
Read::$fixtures = array_fill_keys(array_keys($fixture), array());
ob_start(); require DIR.'includes/paginas/acoes_sociais_ambientais.php'; $html=ob_get_clean();
verify(str_contains($html,'As informações sobre nossas ações') && str_contains($html,'Ainda não há notícias'), 'Empty content and news states');
verify(!str_contains($html,'href="#acoes-voluntariado"') && !str_contains($html,'<dialog'), 'No empty section links or dialog');
Read::$fixtures = $fixture; Read::$fixtures['galeria_acao'] = array_slice($fixture['galeria_acao'],0,1);
ob_start(); require DIR.'includes/paginas/acoes_sociais_ambientais.php'; $html=ob_get_clean();
verify(substr_count($html,'class="about-slide"') === 1, 'Single image');
Read::$fixtures = array('pagina_acoes_sociais_ambientais'=>array(array('bloco4'=>'Informação isolada')), 'galeria_acao'=>array(), 'noticia'=>array());
ob_start(); require DIR.'includes/paginas/acoes_sociais_ambientais.php'; $html=ob_get_clean();
verify(str_contains($html,'Informação isolada') && str_contains($html,'id="acoes-voluntariado"') && !str_contains($html,'<dialog'), 'Partial content without gallery');
Read::$fixtures = $fixture;
Read::$fixtures['pagina_acoes_sociais_ambientais'][0]['bloco1'] = '<script>evil()</script><p onclick="evil()">Texto seguro</p>';
Read::$fixtures['pagina_acoes_sociais_ambientais'][0]['img1'] = 'javascript:evil()';
Read::$fixtures['galeria_acao'] = array(array('img'=>'javascript:evil()','descricao'=>'Bad'));
Read::$fixtures['noticia'] = array(array('titulo'=>'<script>evil()</script>','subtitulo'=>'<b>Resumo seguro</b>','link'=>'exemplo','img'=>'javascript:evil()','data_criacao'=>'invalid'));
ob_start(); require DIR.'includes/paginas/acoes_sociais_ambientais.php'; $html=ob_get_clean();
verify(!str_contains($html,'<script>') && !str_contains($html,'onclick=') && str_contains($html,'Texto seguro'), 'Sanitize content');
verify(!str_contains($html,'javascript:') && !str_contains($html,'<dialog'), 'Reject unsafe feature, gallery and news images');
verify(str_contains($html,'&lt;script&gt;') && str_contains($html,'Resumo seguro'), 'Escape news metadata');
verify(!str_contains($html,'<time') && !str_contains($html,'1970'), 'Do not fabricate invalid dates');
$r_DIR['page'] = 'acoes_sociais_ambientais';
ob_start(); require DIR.'includes/header.php'; $html=ob_get_clean();
verify(!str_contains($html,'jQuery') && str_contains($html,'social-actions.css'), 'Underscore route uses modern assets');
echo 'OK: ' . ($count-$before) . " social-actions checks.\n";
