<script>
(async()=>{
const root=document.querySelector('[data-gallery-admin]'),id=Number(root.dataset.id),mode=root.dataset.mode,form=root.querySelector('form'),feedback=root.querySelector('.admin-feedback');let photos=[],busy=false;
const note=(text,bad=false)=>{feedback.className='admin-feedback alert alert-'+(bad?'danger':'success');feedback.textContent=text;};
async function api(action,body){const url='galeria-api.php'+(body?'':'?acao='+action+'&id_galeria='+id);const options=body?{method:'POST',headers:{'X-CSRF-Token':document.querySelector('meta[name="csrf-token"]').content},body}:{};if(body){body.set('acao',action);body.set('id_galeria',id);}const response=await fetch(url,options);if(response.status===401){location.assign('index.php');throw Error('Sessão expirada.');}const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||'Não foi possível carregar ou salvar a galeria. Verifique a atualização do banco e tente novamente.');return result;}
function render(){const grid=root.querySelector('[data-gallery-photos]');grid.replaceChildren();if(!photos.length){const p=document.createElement('p');p.textContent='Esta galeria ainda não possui imagens. Use o campo acima para adicionar.';grid.append(p);}photos.forEach((photo,index)=>{const card=document.createElement('article');card.className='gallery-card';const img=document.createElement('img');if(['arquivos/','resources/'].some(prefix=>String(photo.url||'').startsWith(prefix)))img.src='../'+photo.url;img.alt=photo.legenda||'Imagem '+(index+1);card.append(img);const label=document.createElement('label');label.textContent='Legenda '+(index+1);const field=document.createElement('input');field.className='form-control';field.maxLength=255;field.value=photo.legenda||'';field.oninput=()=>{photo.legenda=field.value;document.sclDirty=true;};label.append(field);card.append(label);const actions=document.createElement('div');actions.className='d-flex gap-2 mt-3';for(const [text,delta]of [['← Mover antes',-1],['Mover depois →',1]]){const button=document.createElement('button');button.type='button';button.className='btn btn-default btn-sm';button.textContent=text;button.disabled=index+delta<0||index+delta>=photos.length;button.onclick=()=>{[photos[index],photos[index+delta]]=[photos[index+delta],photos[index]];document.sclDirty=true;render();};actions.append(button);}const remove=document.createElement('button');remove.type='button';remove.className='btn btn-outline-danger btn-sm';remove.textContent='Remover';remove.onclick=()=>{photos.splice(index,1);document.sclDirty=true;render();};actions.append(remove);card.append(actions);grid.append(card);});}
try{if(mode==='index'){const list=await api('list');const tbody=root.querySelector('tbody');for(const item of list){const tr=document.createElement('tr');tr.insertCell().textContent=item.nome;tr.insertCell().textContent=item.total;const td=tr.insertCell();const edit=document.createElement('a');edit.href='painel.php?exe=galeria/update&id_galeria='+Number(item.id_galeria);edit.className='btn btn-default btn-sm';edit.textContent='Editar imagens';td.append(edit);const remove=document.createElement('button');remove.type='button';remove.className='btn btn-outline-danger btn-sm ms-2';remove.textContent='Excluir';remove.onclick=()=>sclConfirm({message:'Excluir a galeria? As páginas que a utilizam deixarão de exibir suas imagens. Os arquivos originais serão preservados.',callback:async yes=>{if(!yes)return;try{const body=new FormData();body.set('acao','delete');body.set('id_galeria',item.id_galeria);const response=await fetch('galeria-api.php',{method:'POST',headers:{'X-CSRF-Token':document.querySelector('meta[name="csrf-token"]').content},body});if(!response.ok)throw Error('Não foi possível excluir.');location.reload();}catch(e){note(e.message,true);}}});td.append(remove);tbody.append(tr);}new DataTable(root.querySelector('table'),{columnDefs:[{targets:2,orderable:false}],language:{emptyTable:'Nenhuma galeria cadastrada.'}});return;}
if(id){form.hidden=true;const data=await api('get');form.elements.nome.value=data.gallery.nome;photos=data.photos;render();form.hidden=false;const upload=root.querySelector('#gallery-files');upload.onchange=async()=>{if(busy)return;const files=[...upload.files];if(files.some(f=>f.size>10*1024*1024||!['image/jpeg','image/png'].includes(f.type))){note('Selecione somente imagens JPG/PNG de até 10 MB.',true);return;}busy=true;const button=form.querySelector('[type="submit"]');button.disabled=upload.disabled=true;const progress=root.querySelector('progress');progress.max=files.length;progress.value=0;progress.hidden=false;try{for(const file of files){const body=new FormData();body.set('image',file);photos.push(await api('upload',body));progress.value++;render();}note('Imagens enviadas. Revise as legendas e salve a sequência.');}catch(e){note(e.message,true);}finally{busy=false;button.disabled=upload.disabled=false;upload.value='';progress.hidden=true;}};}
form.onsubmit=async event=>{event.preventDefault();if(busy||!form.reportValidity())return;busy=true;const button=form.querySelector('[type="submit"]');button.disabled=true;try{const body=new FormData();body.set('nome',form.elements.nome.value);body.set('photos',JSON.stringify(photos.map(p=>({id_anexo:p.id_anexo,legenda:p.legenda||''}))));const result=await api(id?'save':'create',body);document.sclDirty=false;if(!id)location.assign('painel.php?exe=galeria/update&id_galeria='+result.id);else note('Galeria, legendas e ordem salvas.');}catch(e){note(e.message,true);}finally{busy=false;button.disabled=false;}};
}catch(e){note(e.message,true);}
})();
</script>