<script>
(async function(){
 const root=document.querySelector('[data-records]'),c=JSON.parse(root.dataset.records),form=root.querySelector('form'),feedback=root.querySelector('.admin-feedback');
 const actions={usuario:['listUsers','getUser','createUser','updateUser','excluiUser'],banner:['getListBanner','GetBanner','NewBanner','UpdateBanner','DeleteBanner'],noticias:['getListNoticia','GetNoticia','NewNoticia','UpdateNoticia','DeleteNoticia']}[c.kind];
 const endpoint='webservices/'+c.kind+'/servico.php';let records=[],table,loaded={};
 function note(message,bad=false){feedback.textContent=message;feedback.className='admin-feedback alert alert-'+(bad?'danger':'success');feedback.scrollIntoView({block:'nearest'});}
 async function api(action,data={}){const body=data instanceof FormData?data:new URLSearchParams(data);body.set('acao',action);const response=await fetch(endpoint,{method:'POST',headers:{'X-CSRF-Token':document.querySelector('meta[name="csrf-token"]').content},body});if(response.status===401){location.assign('index.php');throw Error('Sessão expirada.');}if(!response.ok)throw Error(({409:'Já existe um usuário ou e-mail com esses dados.',422:'Confira os campos obrigatórios, a senha e o arquivo selecionado.'})[response.status]||'Não foi possível concluir a operação. Tente novamente.');return response.text();}
 function image(url){return ['arquivos/','resources/'].some(prefix=>String(url||'').startsWith(prefix))?'../'+url:'';}
 function idData(id){return {[c.kind==='banner'?'IdBanner':c.kind==='noticias'?'IdNoticia':'id_usuario']:id};}
 function render(){if(table)table.destroy();const tbody=root.querySelector('tbody');tbody.replaceChildren();const status=root.querySelector('[data-status-filter]').value;for(const item of records.filter(r=>status===''||String(r.status)===status)){const row=document.createElement('tr');let cell=row.insertCell();cell.textContent=item[c.kind==='usuario'?'nome':'titulo'];cell=row.insertCell();if(c.kind==='usuario')cell.textContent=item.email||'';else if(image(item.img)){const img=document.createElement('img');img.src=image(item.img);img.alt='';img.className='list-thumbnail';cell.append(img);}cell=row.insertCell();const badge=document.createElement('span');badge.className='label label-'+(Number(item.status)?'success':'default');badge.textContent=Number(item.status)?(c.kind==='usuario'?'Ativo':'Publicado'):(c.kind==='usuario'?'Inativo':'Rascunho');cell.append(badge);cell=row.insertCell();const edit=document.createElement('a');edit.className='btn btn-default btn-sm';edit.href='painel.php?exe='+c.kind+'/update&'+c.idKey+'='+Number(item[c.idKey]);edit.textContent='Editar';cell.append(edit);const remove=document.createElement('button');remove.type='button';remove.className='btn btn-outline-danger btn-sm ms-2';remove.textContent='Excluir';remove.onclick=()=>sclConfirm({message:'Excluir este registro? Esta ação não pode ser desfeita pelo painel.',callback:async yes=>{if(!yes)return;remove.disabled=true;try{const result=await api(actions[4],idData(item[c.idKey]));if(!/^(1|ok)$/.test(result.trim()))throw Error('O registro não foi excluído.');await load();note('Registro excluído.');}catch(e){note(e.message,true);}finally{remove.disabled=false;}}});cell.append(remove);tbody.append(row);}table=new DataTable(root.querySelector('table'),{order:[[0,'asc']],columnDefs:[{targets:[1,3],orderable:false}],language:{emptyTable:'Nenhum registro nesta situação.'}});root.querySelector('[data-record-count]').textContent=records.length+' registros cadastrados';}
 async function load(){const data=JSON.parse(await api(actions[0]));records=Array.isArray(data)?data:[];render();}
 try{
 if(c.mode==='index'){root.querySelector('[data-status-filter]').onchange=render;root.querySelector('[data-record-refresh]').onclick=()=>load().catch(e=>note(e.message,true));await load();return;}
 if(c.mode==='update'){let data=JSON.parse(await api(actions[1],idData(c.id)));loaded=Array.isArray(data)?data[0]:data;if(!loaded)throw Error('Registro não encontrado.');for(const [key,value]of Object.entries(loaded)){const field=form.elements.namedItem(key);if(!field||field.type==='file'||field.type==='password')continue;if(field.type==='checkbox')field.checked=Number(value)===1;else field.value=value??'';}const preview=root.querySelector('[data-cover]');if(image(loaded.img)){preview.src=image(loaded.img);preview.hidden=false;}}
 if(c.kind==='noticias'){const response=await fetch(endpoint+'?q=');if(!response.ok)throw Error('Não foi possível carregar as categorias.');const categories=await response.json();const selected=c.id?JSON.parse(await api('getTagsNoticia',{id_noticia:c.id})):[];const select=form.elements.namedItem('id_tag[]');for(const category of categories||[]){if(!String(category.id).trim())continue;const option=new Option(category.text,category.id,false,Array.isArray(selected)&&selected.some(x=>String(x.id_tag)===String(category.id)));select.add(option);}new TomSelect(select,{create:true,plugins:['remove_button'],placeholder:'Selecione ou adicione uma categoria'});SCLEditor.replace('record-description');}
 form.hidden=false;window.sclRefreshCounters?.();
 const photo=form.querySelector('input[type="file"]');photo.onchange=()=>{if(!photo.files[0])return;if(photo.files[0].size>10*1024*1024){photo.value='';note('Selecione uma imagem de até 10 MB.',true);return;}const preview=root.querySelector('[data-cover]');if(preview.dataset.objectUrl)URL.revokeObjectURL(preview.dataset.objectUrl);preview.src=preview.dataset.objectUrl=URL.createObjectURL(photo.files[0]);preview.hidden=false;};
 form.onsubmit=async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type="submit"]');button.disabled=true;try{if(c.kind==='noticias')form.elements.descricao.value=SCLEditor.instances['record-description'].getData();const body=new FormData(form);if(c.id){body.set(c.idKey,c.id);if(c.kind!=='usuario')body.set('img',loaded.img||'');}if(c.self)body.set('status','1');const result=(await api(actions[c.id?'3':'2'],body)).trim();if(!/^[1-9][0-9]*$/.test(result))throw Error(result.replace(/<[^>]*>/g,'').slice(0,200)||'Não foi possível salvar.');document.sclDirty=false;if(c.self){location.assign('index.php');return;}if(!c.id){location.assign('painel.php?exe='+c.kind+'/update&'+c.idKey+'='+result);return;}note('Alterações salvas com sucesso.');}catch(e){note(e.message,true);}finally{button.disabled=false;}};
 }catch(e){note(e.message,true);}
})();
</script>